### PR TITLE
In success cases, fix the return value to send 'next' as true

### PR DESCRIPTION
**Pull request by vikaschoudhary16**
This PR is introducing handleResponse which is required if guest is run on a proxy like envoy. On proxies, handleResponse gets invoked by proxy to handle response from the backened. Currently tck is assuming only middleware mode, and therefore it is handling response as well from the handleRequest.

### CODE REVIEW

**Review by anuraaga — COMMENTED** [review]
Don't remember well, but as some context, IIRC it was intended for response manipulation with http-wasm to work even if it happens in the handleRequest (host should buffer it). Currently we have `resp.Headers().Set` both on lines 112 and 224 and I'm not sure how to reason about it being in two spots.

And for reference, we ran the TCK with mosn here, and IIUC, that is the same type of "proxy not middleware" discussed in the PR title, AFAIK, it's supposed to be already possible

https://github.com/mosn/mosn/pull/2168/files#diff-5f1b775a2290cf89e57959603383ec96c180182fcda5c8e68ee434eecdc72904R9

What is missing is any sort of test coverage of response processing, so I guess the intent is to add cases like `get_header_values/response/foo` in `handleResponse`?

**Comment by vikaschoudhary16** [comment]
> it was intended for response manipulation with http-wasm to work even if it happens in the handleRequest (host should buffer it)

**Comment by vikaschoudhary16** [comment]
>What is missing is any sort of test coverage of response processing, so I guess the intent is to add cases like get_header_values/response/foo in handleResponse?

This can be done in followup. For now, I am trying exisitng tests against envoy

**Review by anuraaga — APPROVED** [review]

**Comment by jcchavezs** [comment]
I am usually reluctant to do changes in code that does not affect the repository itself. In this specific case we are changing `tck/gues/main.go` for no apparent reason (I know there is an explanation) **for the project**, questions like "why didn't it fail in the past" or "why do I have to change it here and not somewhere else" arrives to me. Could we add a minimal test to make sure we don't do do arbitrary changes that break this liability in the future?

**Comment by anuraaga** [comment]
For reference, we have a test using the proxy pattern here

https://github.com/http-wasm/http-wasm-tck/blob/main/e2e/e2e_test.go#L22

It's true I wonder what it is about that test that doesn't trigger the problem found here, if that test also needs to be updated to demonstrate the problem that will be nice to do.

**Comment by jcchavezs** [comment]
Any movement on this @vikaschoudhary16 ?

**Comment by vikaschoudhary16** [comment]
Hey @jcchavezs , did not get chance last week to work on this. Will work this week.

**Comment by vikaschoudhary16** [comment]
I got chance to spend some time understanding tck tests. 
>we have a test using the proxy pattern here

Current tests are on middleware pattern. For request related methods, when ctxNext is returned 0, middleware skips forwarding request to backened and replies locally with a 200. This is not how it should be. For the tests like TestGetURI or TestGetMethod, tests should not skip calling backened.
image

When run with a proxy like envoy, ctxNext==0 is not treated as "send local response"(which the current tests are doing)

**Comment by anuraaga** [comment]
Ah OK, the tests happen to work with http status 200 from the local response even though we intended it to be the backend one which is the same. It reminds me of @jcchavezs's suggestion somewhere else to never use 200 in test cases, we may change it in a different PR. But this PR makes sense, thanks for the explanation

**Comment by jcchavezs** [comment]
Thanks for the detailed explanation @vikaschoudhary16, shall we proceed with this PR?

>  we may change it in a different PR

up to that @anuraaga ?

**Comment by vikaschoudhary16** [comment]
> shall we proceed with this PR?

yeah, I think so.

**Review by jcchavezs — APPROVED** [review]

**Pull request merged**
